// apps/svelte/src/routes/posts/[id]/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { PageData } from './$types';

	export let data: PageData;
</script>

<main>
	<a href="/posts">All Posts</a>
	<form action="?/deletePost" method="POST" use:enhance>
		<input type="hidden" name="id" value={data.post.id} />
		<button type="submit">Delete Post</button>
	</form>
	<h1>{data.post.title}</h1>
	<p>{data.post.body}</p>
</main>

// apps/next-app/src/app/posts/[id]/page.tsx
import { redirect } from "next/navigation"
import prisma from "../../utls/prisma"
import Link from "next/link"

export default async function Page({ params }: { params: { id: string }}) {
  const post = await prisma.post.findUnique({
    where: {
      id: params.id
    }
  })

  if (!post) {
    return redirect('/posts')
  }

  async function deletePost() {
    'use server'
    await prisma.post.delete({ where: { id: params.id }})

    return redirect('/posts')
  }

  return (
    <main>
      <Link href="/posts">Posts</Link>
      <h1>{post.title}</h1>
      <p>{post.body}</p>
      <form action={deletePost}>
        <button type="submit">Delete</button>
      </form>
    </main>
  )
}
