// apps/svelte/src/routes/posts/+page.svelte
<script lang="ts">
	import type { PageData, ActionData } from './$types';

	export let data: PageData;
	export let { posts } = data;
</script>

<svelte:head>
	<title>Svelte</title>
</svelte:head>

<main>
	<h1>Posts</h1>

	<form method="POST" action="?/createPost">
		<input type="text" name="title" />
		<input type="text" name="body" />
		<button type="submit">Create Post</button>
	</form>

	<ul>
		{#each posts as post}
			<li>
				<a href="/posts/{post.id}">
					{post.title}
				</a>
			</li>
		{/each}
	</ul>
</main>

// apps/next-pages/src/pages/posts/index.tsx
import prisma from "@/lib/prisma"
import { Post } from "@prisma/client"
import { GetServerSideProps } from "next"
import Link from "next/link"


export const getServerSideProps: GetServerSideProps<{ posts: Post[] }> = async () => {
  const posts = await prisma.post.findMany()

  return {
    props: {
      posts
    }
  }
}

interface PageProps {
  posts: Post[]
}

export default function Page({
  posts
}: PageProps) {
  return (
    <main>
      <h1>Posts</h1>
      <form action="/api/posts" method="POST">
        <input type="text" name="title" />
        <input type="text" name="body" />
        <button type="submit">Submit</button>
      </form>
      <ul>
        {posts.map((post: Post) => {
          return (
            <li key={post.id}>
              <Link href={`/posts/${post.id}`}>{post.title}</Link>
            </li>
          )
        })}
      </ul>
    </main>
  )
}
